name: 'Claude Code OAuth Login'
description: 'Authenticate with Claude Code using OAuth 2.0 flow'
author: 'Guillaume Raille <guillaume.raille@gmail.com>'
branding:
  icon: 'log-in'
  color: 'orange'

inputs:
  code:
    description: 'Authorization code from Claude (leave empty for step 1)'
    required: false
    default: ''

outputs:
  success:
    description: 'Whether the OAuth login was successful'
    value: ${{ steps.oauth.outputs.success }}
  expires_at:
    description: 'Token expiration timestamp (milliseconds)'
    value: ${{ steps.oauth.outputs.expires_at }}

runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.2.17

    - name: Install Dependencies
      shell: bash
      run: |
        cd ${GITHUB_ACTION_PATH}
        bun install

    - name: Cache OAuth State
      uses: actions/cache@v4
      with:
        path: ${{ github.action_path }}/claude_oauth_state.json
        key: claude-oauth-state

    - name: Run OAuth Flow
      id: oauth
      shell: bash
      run: |
        cd ${GITHUB_ACTION_PATH}
        if [ -z "${{ inputs.code }}" ]; then
          echo "ðŸ”— **STEP 1: Generate Login URL**"
          echo ""
          echo "Running OAuth URL generation..."
          echo ""
          
          # Generate the login URL
          LOGIN_URL=$(bun run index.ts)
          
          echo "âœ… **Login URL Generated Successfully!**"
          echo ""
          echo "ðŸ“‹ **Next Steps:**"
          echo "1. Click or copy this URL and open it in your browser:"
          echo "   ðŸ‘‰ $LOGIN_URL"
          echo ""
          echo "2. Sign in to Claude and authorize the application"
          echo ""
          echo "3. After authorization, you'll be redirected to a page with an authorization code"
          echo "   The URL will look like: https://console.anthropic.com/oauth/code/callback?code=YOUR_CODE_HERE"
          echo ""
          echo "4. Copy the authorization code (the part after 'code=')"
          echo ""
          echo "5. Run this GitHub Action again with the code:"
          echo "   - Go to Actions tab â†’ Claude Code OAuth Login â†’ Run workflow"
          echo "   - Paste the authorization code in the 'code' input field"
          echo "   - Click 'Run workflow'"
          echo ""
          echo "ðŸ”„ **Ready for Step 2!**"
          echo "success=pending" >> $GITHUB_OUTPUT
        else
          echo "ðŸ” **STEP 2: Exchange Code for Tokens**"
          echo ""
          echo "Authorization code provided: ${MASK_CODE}"
          echo ""
          
          # Exchange the code for tokens and capture outputs
          if bun run index.ts "${{ inputs.code }}"; then
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "success=false" >> $GITHUB_OUTPUT
          fi
        fi
      env:
        MASK_CODE: ${{ inputs.code != '' && '***REDACTED***' || 'Not provided' }}
